import Benchmark

let someText = """
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed diam neque, fringilla in consectetur nec, finibus a dolor. Cras pulvinar, ligula ut aliquet placerat, nisl nisi ultricies odio, nec tincidunt dolor erat in lacus. Nulla facilisi. Suspendisse potenti. Suspendisse potenti. Suspendisse potenti. Sed at nisl id metus interdum interdum. Nullam eget nunc sed ipsum aliquam ultricies. Aliquam erat volutpat. Fusce eget justo in ante aliquet condimentum. Aenean bibendum turpis vitae mi maximus, eu ultrices ante lacinia. Sed at elit ullamcorper, porta odio a, molestie nisl. Fusce quis odio ac tortor convallis dapibus. Sed efficitur, tellus vitae ultricies pharetra, lacus ipsum lacinia orci, ut euismod arcu nisi et urna. Phasellus rutrum, ex vitae vulputate laoreet, massa neque consequat felis, quis mattis enim dui eget risus. Duis auctor ultrices ligula, quis rhoncus risus.
    """

@discardableResult
func plusRun() -> String {
    let output =
    "Lorem" + "ipsum" + "dolor" + "sit" + "amet," + "consectetur" + "adipiscing" + "elit." + "Sed" + "diam"
    + "neque," + "fringilla" + "in" + "consectetur" + "nec," + "finibus" + "a" + "dolor." + "Cras" + "pulvinar,"
    + "ligula" + "ut" + "aliquet" + "placerat," + "nisl" + "nisi" + "ultricies" + "odio," + "nec" + "tincidunt"
    + "dolor" + "erat" + "in" + "lacus." + "Nulla" + "facilisi." + "Suspendisse" + "potenti." + "Suspendisse"
    + "potenti." + "Suspendisse" + "potenti." + "Sed" + "at" + "nisl" + "id" + "metus" + "interdum" + "interdum."
    + "Nullam" + "eget" + "nunc" + "sed" + "ipsum" + "aliquam" + "ultricies." + "Aliquam" + "erat" + "volutpat."
    + "Fusce" + "eget" + "justo" + "in" + "ante" + "aliquet" + "condimentum." + "Aenean" + "bibendum" + "turpis"
    + "vitae" + "mi" + "maximus," + "eu" + "ultrices" + "ante" + "lacinia." + "Sed" + "at" + "elit" + "ullamcorper,"
    + "porta" + "odio" + "a," + "molestie" + "nisl." + "Fusce" + "quis" + "odio" + "ac" + "tortor" + "convallis"
    + "dapibus." + "Sed" + "efficitur," + "tellus" + "vitae" + "ultricies" + "pharetra," + "lacus" + "ipsum"
    + "lacinia" + "orci," + "ut" + "euismod" + "arcu" + "nisi" + "et" + "urna." + "Phasellus" + "rutrum," + "ex"
    + "vitae" + "vulputate" + "laoreet," + "massa" + "neque" + "consequat" + "felis," + "quis" + "mattis" + "enim"
    + "dui" + "eget" + "risus." + "Duis" + "auctor" + "ultrices" + "ligula," + "quis" + "rhoncus" + "risus."
    return output
}

@discardableResult
func appendRun() -> String {
    var lorem = "Lorem"
    lorem.append("ipsum")
    lorem.append("dolor")
    lorem.append("sit")
    lorem.append("amet,")
    lorem.append("consectetur")
    lorem.append("adipiscing")
    lorem.append("elit.")
    lorem.append("Sed")
    lorem.append("diam")
    lorem.append("neque,")
    lorem.append("fringilla")
    lorem.append("in")
    lorem.append("consectetur")
    lorem.append("nec,")
    lorem.append("finibus")
    lorem.append("a")
    lorem.append("dolor.")
    lorem.append("Cras")
    lorem.append("pulvinar,")
    lorem.append("ligula")
    lorem.append("ut")
    lorem.append("aliquet")
    lorem.append("placerat,")
    lorem.append("nisl")
    lorem.append("nisi")
    lorem.append("ultricies")
    lorem.append("odio,")
    lorem.append("nec")
    lorem.append("tincidunt")
    lorem.append("dolor")
    lorem.append("erat")
    lorem.append("in")
    lorem.append("lacus.")
    lorem.append("Nulla")
    lorem.append("facilisi.")
    lorem.append("Suspendisse")
    lorem.append("potenti.")
    lorem.append("Suspendisse")
    lorem.append("potenti.")
    lorem.append("Suspendisse")
    lorem.append("potenti.")
    lorem.append("Sed")
    lorem.append("at")
    lorem.append("nisl")
    lorem.append("id")
    lorem.append("metus")
    lorem.append("interdum")
    lorem.append("interdum.")
    lorem.append("Nullam")
    lorem.append("eget")
    lorem.append("nunc")
    lorem.append("sed")
    lorem.append("ipsum")
    lorem.append("aliquam")
    lorem.append("ultricies.")
    lorem.append("Aliquam")
    lorem.append("erat")
    lorem.append("volutpat.")
    lorem.append("Fusce")
    lorem.append("eget")
    lorem.append("justo")
    lorem.append("in")
    lorem.append("ante")
    lorem.append("aliquet")
    lorem.append("condimentum.")
    lorem.append("Aenean")
    lorem.append("bibendum")
    lorem.append("turpis")
    lorem.append("vitae")
    lorem.append("mi")
    lorem.append("maximus,")
    lorem.append("eu")
    lorem.append("ultrices")
    lorem.append("ante")
    lorem.append("lacinia.")
    lorem.append("Sed")
    lorem.append("at")
    lorem.append("elit")
    lorem.append("ullamcorper,")
    lorem.append("porta")
    lorem.append("odio")
    lorem.append("a,")
    lorem.append("molestie")
    lorem.append("nisl.")
    lorem.append("Fusce")
    lorem.append("quis")
    lorem.append("odio")
    lorem.append("ac")
    lorem.append("tortor")
    lorem.append("convallis")
    lorem.append("dapibus.")
    lorem.append("Sed")
    lorem.append("efficitur,")
    lorem.append("tellus")
    lorem.append("vitae")
    lorem.append("ultricies")
    lorem.append("pharetra,")
    lorem.append("lacus")
    lorem.append("ipsum")
    lorem.append("lacinia")
    lorem.append("orci,")
    lorem.append("ut")
    lorem.append("euismod")
    lorem.append("arcu")
    lorem.append("nisi")
    lorem.append("et")
    lorem.append("urna.")
    lorem.append("Phasellus")
    lorem.append("rutrum,")
    lorem.append("ex")
    lorem.append("vitae")
    lorem.append("vulputate")
    lorem.append("laoreet,")
    lorem.append("massa")
    lorem.append("neque")
    lorem.append("consequat")
    lorem.append("felis,")
    lorem.append("quis")
    lorem.append("mattis")
    lorem.append("enim")
    lorem.append("dui")
    lorem.append("eget")
    lorem.append("risus.")
    lorem.append("Duis")
    lorem.append("auctor")
    lorem.append("ultrices")
    lorem.append("ligula,")
    lorem.append("quis")
    lorem.append("rhoncus")
    lorem.append("risus.")
    return lorem
}

benchmark("Plus operator in a function") {
    let a = plusRun()
}

benchmark("Plus operator called inside benchmark") {
    let output =
    "Lorem" + "ipsum" + "dolor" + "sit" + "amet," + "consectetur" + "adipiscing" + "elit." + "Sed" + "diam"
    + "neque," + "fringilla" + "in" + "consectetur" + "nec," + "finibus" + "a" + "dolor." + "Cras" + "pulvinar,"
    + "ligula" + "ut" + "aliquet" + "placerat," + "nisl" + "nisi" + "ultricies" + "odio," + "nec" + "tincidunt"
    + "dolor" + "erat" + "in" + "lacus." + "Nulla" + "facilisi." + "Suspendisse" + "potenti." + "Suspendisse"
    + "potenti." + "Suspendisse" + "potenti." + "Sed" + "at" + "nisl" + "id" + "metus" + "interdum" + "interdum."
    + "Nullam" + "eget" + "nunc" + "sed" + "ipsum" + "aliquam" + "ultricies." + "Aliquam" + "erat" + "volutpat."
    + "Fusce" + "eget" + "justo" + "in" + "ante" + "aliquet" + "condimentum." + "Aenean" + "bibendum" + "turpis"
    + "vitae" + "mi" + "maximus," + "eu" + "ultrices" + "ante" + "lacinia." + "Sed" + "at" + "elit" + "ullamcorper,"
    + "porta" + "odio" + "a," + "molestie" + "nisl." + "Fusce" + "quis" + "odio" + "ac" + "tortor" + "convallis"
    + "dapibus." + "Sed" + "efficitur," + "tellus" + "vitae" + "ultricies" + "pharetra," + "lacus" + "ipsum"
    + "lacinia" + "orci," + "ut" + "euismod" + "arcu" + "nisi" + "et" + "urna." + "Phasellus" + "rutrum," + "ex"
    + "vitae" + "vulputate" + "laoreet," + "massa" + "neque" + "consequat" + "felis," + "quis" + "mattis" + "enim"
    + "dui" + "eget" + "risus." + "Duis" + "auctor" + "ultrices" + "ligula," + "quis" + "rhoncus" + "risus."
}

benchmark("Append in a function") {
    let a = appendRun()
}

benchmark("Append called inside benchmark") {
    var lorem = "Lorem"
    lorem.append("ipsum")
    lorem.append("dolor")
    lorem.append("sit")
    lorem.append("amet,")
    lorem.append("consectetur")
    lorem.append("adipiscing")
    lorem.append("elit.")
    lorem.append("Sed")
    lorem.append("diam")
    lorem.append("neque,")
    lorem.append("fringilla")
    lorem.append("in")
    lorem.append("consectetur")
    lorem.append("nec,")
    lorem.append("finibus")
    lorem.append("a")
    lorem.append("dolor.")
    lorem.append("Cras")
    lorem.append("pulvinar,")
    lorem.append("ligula")
    lorem.append("ut")
    lorem.append("aliquet")
    lorem.append("placerat,")
    lorem.append("nisl")
    lorem.append("nisi")
    lorem.append("ultricies")
    lorem.append("odio,")
    lorem.append("nec")
    lorem.append("tincidunt")
    lorem.append("dolor")
    lorem.append("erat")
    lorem.append("in")
    lorem.append("lacus.")
    lorem.append("Nulla")
    lorem.append("facilisi.")
    lorem.append("Suspendisse")
    lorem.append("potenti.")
    lorem.append("Suspendisse")
    lorem.append("potenti.")
    lorem.append("Suspendisse")
    lorem.append("potenti.")
    lorem.append("Sed")
    lorem.append("at")
    lorem.append("nisl")
    lorem.append("id")
    lorem.append("metus")
    lorem.append("interdum")
    lorem.append("interdum.")
    lorem.append("Nullam")
    lorem.append("eget")
    lorem.append("nunc")
    lorem.append("sed")
    lorem.append("ipsum")
    lorem.append("aliquam")
    lorem.append("ultricies.")
    lorem.append("Aliquam")
    lorem.append("erat")
    lorem.append("volutpat.")
    lorem.append("Fusce")
    lorem.append("eget")
    lorem.append("justo")
    lorem.append("in")
    lorem.append("ante")
    lorem.append("aliquet")
    lorem.append("condimentum.")
    lorem.append("Aenean")
    lorem.append("bibendum")
    lorem.append("turpis")
    lorem.append("vitae")
    lorem.append("mi")
    lorem.append("maximus,")
    lorem.append("eu")
    lorem.append("ultrices")
    lorem.append("ante")
    lorem.append("lacinia.")
    lorem.append("Sed")
    lorem.append("at")
    lorem.append("elit")
    lorem.append("ullamcorper,")
    lorem.append("porta")
    lorem.append("odio")
    lorem.append("a,")
    lorem.append("molestie")
    lorem.append("nisl.")
    lorem.append("Fusce")
    lorem.append("quis")
    lorem.append("odio")
    lorem.append("ac")
    lorem.append("tortor")
    lorem.append("convallis")
    lorem.append("dapibus.")
    lorem.append("Sed")
    lorem.append("efficitur,")
    lorem.append("tellus")
    lorem.append("vitae")
    lorem.append("ultricies")
    lorem.append("pharetra,")
    lorem.append("lacus")
    lorem.append("ipsum")
    lorem.append("lacinia")
    lorem.append("orci,")
    lorem.append("ut")
    lorem.append("euismod")
    lorem.append("arcu")
    lorem.append("nisi")
    lorem.append("et")
    lorem.append("urna.")
    lorem.append("Phasellus")
    lorem.append("rutrum,")
    lorem.append("ex")
    lorem.append("vitae")
    lorem.append("vulputate")
    lorem.append("laoreet,")
    lorem.append("massa")
    lorem.append("neque")
    lorem.append("consequat")
    lorem.append("felis,")
    lorem.append("quis")
    lorem.append("mattis")
    lorem.append("enim")
    lorem.append("dui")
    lorem.append("eget")
    lorem.append("risus.")
    lorem.append("Duis")
    lorem.append("auctor")
    lorem.append("ultrices")
    lorem.append("ligula,")
    lorem.append("quis")
    lorem.append("rhoncus")
    lorem.append("risus.")
}

benchmark("Interpolation") {
    let a = "\("Lorem") \("ipsum") \("dolor") \("sit") \("amet,") \("consectetur") \("adipiscing") \("elit.") \("Sed") \("diam") \("neque,") \("fringilla") \("in") \("consectetur") \("nec,") \("finibus") \("a") \("dolor.") \("Cras") \("pulvinar,") \("ligula") \("ut") \("aliquet") \("placerat,") \("nisl") \("nisi") \("ultricies") \("odio,") \("nec") \("tincidunt") \("dolor") \("erat") \("in") \("lacus.") \("Nulla") \("facilisi.") \("Suspendisse") \("potenti.") \("Suspendisse") \("potenti.") \("Suspendisse") \("potenti.") \("Sed") \("at") \("nisl") \("id") \("metus") \("interdum") \("interdum.") \("Nullam") \("eget") \("nunc") \("sed") \("ipsum") \("aliquam") \("ultricies.") \("Aliquam") \("erat") \("volutpat.") \("Fusce") \("eget") \("justo") \("in") \("ante") \("aliquet") \("condimentum.") \("Aenean") \("bibendum") \("turpis") \("vitae") \("mi") \("maximus,") \("eu") \("ultrices") \("ante") \("lacinia.") \("Sed") \("at") \("elit") \("ullamcorper,") \("porta") \("odio") \("a,") \("molestie") \("nisl.") \("Fusce") \("quis") \("odio") \("ac") \("tortor") \("convallis") \("dapibus.") \("Sed") \("efficitur,") \("tellus") \("vitae") \("ultricies") \("pharetra,") \("lacus") \("ipsum") \("lacinia") \("orci,") \("ut") \("euismod") \("arcu") \("nisi") \("et") \("urna.") \("Phasellus") \("rutrum,") \("ex") \("vitae") \("vulputate") \("laoreet,") \("massa") \("neque") \("consequat") \("felis,") \("quis") \("mattis") \("enim") \("dui") \("eget") \("risus.") \("Duis") \("auctor") \("ultrices") \("ligula,") \("quis") \("rhoncus") \("risus.")"
}

print(plusRun() == appendRun())

Benchmark.main()
